USE [SSA]

GO

INSERT INTO [gestao_reembolso].[DEPARTAMENTO](
	CD_DEPARTAMENTO, 
	DS_DEPARTAMENTO
) VALUES (
	'0000020',
	''
)

GO

INSERT INTO [gestao_reembolso].[SISTEMA](
	DS_SISTEMA
) VALUES (
	'SSAFUNCAO'
)

GO


INSERT INTO [gestao_reembolso].[PRODUTO](
	CD_PRODUTO,
	NM_PRODUTO,
	CD_CARTEIRA,
	ID_SISTEMA
) VALUES (
	'0001',
	'CONSIGNADO',
	'032',
	(SELECT ID_SISTEMA FROM [gestao_reembolso].[SISTEMA] WHERE DS_SISTEMA = 'SSAFUNCAO')
)

GO


INSERT INTO [gestao_reembolso].[CONTA](
	CD_TIPO_CONTA, 
	NO_BANCO, 
	NO_AGENCIA,
	NO_DIGITO_AGENCIA, 
	NO_CONTA
) VALUES (
	'CC',
	'0623',
	'0001',
	'9',
	'0000011019'
)

GO

INSERT INTO [gestao_reembolso].[CONTA_RESERVA](
	ID_CONTA, 
	NO_CNPJ_SACADO,
	NO_SEQUENCIA_SACADO,
	NM_SACADO, 
	CD_TIPO_PESSOA_SACADO
) VALUES (
	@@IDENTITY, 
	'59285411000113',
	'0',
	'BANCO PAN SA',
	'J'
)

GO

INSERT INTO [gestao_reembolso].[COLIGADA](
	CD_COLIGADA, 
	NM_COLIGADA,
	CNPJ_COLIGADA
) VALUES (
	'001',
	'BANCO PAN SA',
	'59285411000113'
)

GO

INSERT INTO [gestao_reembolso].[MENSAGEM_PADRAO](
	ID_PRODUTO, 
	CD_FINALIDADE_SPB,
	IC_CREDITA_CONTA_CORRENTE,
	IC_DEBITA_CONTA_CORRENTE,
	IC_EMITE_RECEBE,
	IC_MESMA_TITULARIDADE, 
	IC_PREVISAO,
	IC_TRANSITA_CONTA_CORRENTE,
	NO_BORDERO, 
	CD_TIPO_LIQUIDACAO
) VALUES (
	(SELECT ID_PRODUTO FROM [gestao_reembolso].[PRODUTO] WHERE CD_PRODUTO = '0001'),
	'00040',
	'N',
	'N',
	'E',
	'N',
	'N',
	'N',
	'0000000',
	'PAG0143'
)

GO

INSERT INTO [gestao_reembolso].[MENSAGEM_COMUNICACAO](
	DS_MENSAGEM_COMUNICACAO,
	CD_TIPO_COMUNICACAO
) VALUES (
	'Aviso Banco Pan: Existe um valor disponivel para reembolso em seu favor. Favor entrar em contato com nossa central de atendimento.',
	'SMS' 
)

GO

INSERT INTO [gestao_reembolso].[MENSAGEM_COMUNICACAO](
	DS_MENSAGEM_COMUNICACAO,
	CD_TIPO_COMUNICACAO
) VALUES (
	'Aviso Banco Pan: Existe um valor disponivel para reembolso em seu favor. Favor entrar em contato com nossa central de atendimento.',
	'CARTA_AR' 
)

GO


INSERT INTO [gestao_reembolso].[SIGLA] (CD_SIGLA, DS_SIGLA, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO)  VALUES  ('CTNI', 'Contrato não integrado', GETDATE(), NULL, '1')
INSERT INTO [gestao_reembolso].[SIGLA] (CD_SIGLA, DS_SIGLA, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO)  VALUES  ('DEB', 'Parcela do mês baixada por débito em conta', GETDATE(), NULL, '1')
INSERT INTO [gestao_reembolso].[SIGLA] (CD_SIGLA, DS_SIGLA, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO)  VALUES  ('CTL', 'Contrato Liquidado', GETDATE(), NULL, '1')
INSERT INTO [gestao_reembolso].[SIGLA] (CD_SIGLA, DS_SIGLA, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO)  VALUES  ('PBX', 'REG INAD', GETDATE(), NULL, '1')
INSERT INTO [gestao_reembolso].[SIGLA] (CD_SIGLA, DS_SIGLA, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO)  VALUES  ('AVB', 'Averbação a maior ou incorreta', GETDATE(), NULL, '1')
INSERT INTO [gestao_reembolso].[SIGLA] (CD_SIGLA, DS_SIGLA, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO)  VALUES  ('EST', 'Estorno HF 302 e HF 309', GETDATE(), NULL, '1')
INSERT INTO [gestao_reembolso].[SIGLA] (CD_SIGLA, DS_SIGLA, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO)  VALUES  ('DCONB', 'Valores ref. à Ouvidoria INSS', GETDATE(), NULL, '1')
INSERT INTO [gestao_reembolso].[SIGLA] (CD_SIGLA, DS_SIGLA, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO)  VALUES  ('DEV TF', 'Devolução de tarifa', GETDATE(), NULL, '1')
INSERT INTO [gestao_reembolso].[SIGLA] (CD_SIGLA, DS_SIGLA, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO)  VALUES  ('SOBRA', 'Sobra de valores', GETDATE(), NULL, '1')

GO


-- Entrada
 INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (1,'BX EMPREGADOR', NULL, '917', 'ENTRADA', '4.9.9.92.00.7 214.8', '4.9.9.92.00.7 216.4',	GETDATE(), NULL, 1)
 INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (2,'DEBITO CONTA', NULL, '917', 'ENTRADA', '4.9.9.92.00.7 214.8', '4.9.9.92.00.7 216.4',	GETDATE(), NULL, 1)
 INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (3,'ASSESSORIA', NULL, '8611', 'ENTRADA', '4.9.9.92.00.7 221.0', '4.9.9.92.00.7 216.4',	GETDATE(), NULL, 1)
 INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (4,'BOLETO ', NULL, '10734', 'ENTRADA', '4.9.9.92.00.7 229.6', '4.9.9.92.00.7 216.4',	GETDATE(), NULL, 1)
 INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (5,'CANC CONTRATO', NULL, '10736', 'ENTRADA', '4.9.9.92.00.7 213.0', '4.9.9.92.00.7 216.4',	GETDATE(), NULL, 1)
 INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (6,'INADIMPLÊNCIA', NULL, '917', 'ENTRADA', '4.9.9.92.00.7 214.8', '4.9.9.92.00.7 216.4',	GETDATE(), NULL, 1)
 INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (7,'ESTORNO HF302', NULL, NULL, 'ENTRADA', NULL, NULL, GETDATE(), NULL, 1)
 INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (8,'DCONB - HF 309', NULL, NULL, 'ENTRADA', NULL, NULL, GETDATE(), NULL, 1)
 INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (9,'DCONB - SELIC', '20391', '917', 'ENTRADA', '8.1.9.99.00.6 765.5', '4.9.9.92.00.7 216.4',	GETDATE(), NULL, 1)
 INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (10,'DEV TARIFA', '20391', '12529', 'ENTRADA', '8.1.9.99.00.6 765.5', '4.9.9.92.00.7 216.4',	GETDATE(), NULL, 1)
 INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (11,'DIVERSOS', NULL, '917', 'ENTRADA', '4.9.9.92.00.7 214.8', '4.9.9.92.00.7 216.4',	GETDATE(), NULL, 1)
 INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (12,'RET USO INTERNO', NULL, NULL, 'ENTRADA', '4.9.9.92.00.7 214.8', '4.9.9.92.00.7 216.4',	GETDATE(), NULL, 1)

-- Saida
INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (1,'DEBITO CONTA', NULL, '2555', 'SAIDA', '4.9.9.92.00.7 216.4', '4.9.9.92.00.7 214.8',	GETDATE(), NULL, 1)
INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (2,'ASSESSORIA', NULL, '10924', 'SAIDA', '4.9.9.92.00.7 216.4', '4.9.9.92.00.7 221.0',	GETDATE(), NULL, 1)
INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (3,'INADIMPLÊNCIA', NULL, '2555', 'SAIDA', '4.9.9.92.00.7 216.4', '4.9.9.92.00.7 214.8',	GETDATE(), NULL, 1)
INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (4,'BOLETO', NULL, '11707', 'SAIDA', '4.9.9.92.00.7 216.4', '4.9.9.92.00.7 229.6',	GETDATE(), NULL, 1)
INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (5,'GLOSA INSS', NULL, '1984', 'SAIDA', '4.9.9.92.00.7 216.4', '1.8.8.92.00.4 741.6',	GETDATE(), NULL, 1)
INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (6,'GLOSA', NULL, '2555', 'SAIDA', '4.9.9.92.00.7 216.4', '4.9.9.92.00.7 214.8',	GETDATE(), NULL, 1)
INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (7,'DIVERSOS', NULL, '2555', 'SAIDA', '4.9.9.92.00.7 216.4', '4.9.9.92.00.7 214.8',	GETDATE(), NULL, 1)
INSERT INTO [gestao_reembolso].[PROCESSO_REGISTRO] (CD_PROCESSO_REGISTRO, DS_PROCESSO_REGISTRO, CD_CENTRO_CUSTO, CD_MODELO_CONTABIL, CD_FLUXO, CD_CONTA_DEBITO, CD_CONTA_CREDITO, DT_INCLUSAO, DT_ALTERACAO, IC_ATIVO) VALUES (12,'RET USO INTERNO', NULL, NULL, 'SAIDA', '4.9.9.92.00.7 214.8', '4.9.9.92.00.7 216.4',	GETDATE(), NULL, 1)

GO

INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('TED CLIENTE','HF PANCRED',100,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB ESPECIE','HF PANCRED',101,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB CHEQUE','HF PANCRED',102,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REAPRESENT OP PARA TED','HF PANCRED',103,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RETORNO OP','HF PANCRED',104,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC MARABRAZ','HF PANCRED',105,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('OP ITAU','HF PANCRED',106,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BOLETO','HF PANCRED',107,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC C&C','HF PANCRED',108,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC TELHANORTE','HF PANCRED',109,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC DICICO','HF PANCRED',110,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('TED STR','HF PANCRED',111,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC CENTER CASTILHO','HF PANCRED',112,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC JOLI','HF PANCRED',113,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC RECESA','HF PANCRED',114,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REFINANCIAMENTO','HF PANCRED',115,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC AGRIZZI','HF PANCRED',116,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC FENICIA','HF PANCRED',117,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC NEUZA ARARAQUARA','HF PANCRED',118,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC TECIANO','HF PANCRED',119,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC BRIZOLARI','HF PANCRED',120,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC KYOLIFE','HF PANCRED',121,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC EMERSON','HF PANCRED',122,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC PISE BEM','HF PANCRED',123,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC MAGAZINE STAR','HF PANCRED',124,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIBER. C. GARANTIDA','HF PANCRED',125,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC JOAO DANIEL','HF PANCRED',126,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC GERUBAL','HF PANCRED',127,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB CONTA GARANTIDA','HF PANCRED',128,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC OLIVEIRA & SIMER','HF PANCRED',129,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('AQUISICAO TERCEIROS','HF PANCRED',130,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC PREDIAL CONSTRUM','HF PANCRED',131,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC CLAUDIO BRISOLAR','HF PANCRED',132,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC CASA DOS MOVEIS','HF PANCRED',133,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC PNET INFORMATICA','HF PANCRED',134,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC SIMARELLI','HF PANCRED',135,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC MKT INFORMATICA','HF PANCRED',136,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC DORIA','HF PANCRED',137,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC EZIEL','HF PANCRED',138,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC TRILOGIA','HF PANCRED',139,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC CRISMAR','HF PANCRED',140,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC TRIBOX','HF PANCRED',141,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC TRIDIMENSIONAL','HF PANCRED',142,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC SEVEN DIGITAL','HF PANCRED',143,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC PC BOX','HF PANCRED',144,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC MEGA BOX','HF PANCRED',145,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC IDEOLOGIA','HF PANCRED',146,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC MEGASTORE','HF PANCRED',147,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC FANTASY','HF PANCRED',148,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC RESAL IND.','HF PANCRED',149,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC MJL COM','HF PANCRED',150,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DOC BANSERV','HF PANCRED',151,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB CP MONTE CRISTO','HF PANCRED',152,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ADTO FILIAL - RECOMP','HF PANCRED',153,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB REFIN INSS','HF PANCRED',154,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REC INSS PROMOTORAS','HF PANCRED',155,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RECOMPRA CP MONTE CR','HF PANCRED',156,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('IMPL REC CETELEM','HF PANCRED',157,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CP ORGÃOS PUBLICOS','HF PANCRED',158,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB CP ORGAOS PUBL','HF PANCRED',159,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CP CDIV INSS','HF PANCRED',160,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB CDIV INSS','HF PANCRED',161,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REAPRESENTAÇÃO DE OP','HF PANCRED',162,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('OP SANTANDER','HF PANCRED',163,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('OP CEF','HF PANCRED',164,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RECOMPRA ORGÃOS PUBL','HF PANCRED',165,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REAPRESENT TED','HF PANCRED',166,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB COMPRA STR','HF PANCRED',167,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REEMBOLSO CORBAN','HF PANCRED',168,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB CP STR','HF PANCRED',169,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB CARTAO CERTERGY','HF PANCRED',170,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB STR BB','HF PANCRED',171,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('OP - BANCO GERADOR','HF PANCRED',172,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REFIN DE PORTABILIDADE','HF PANCRED',173,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REFIN DE PORTABILIDADE PÓ','HF PANCRED',174,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REFIN PORTAB - EXCEÇÃO','HF PANCRED',175,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REFIN PORTAB-PÓS EXCEÇÃO','HF PANCRED',176,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX PREJUIZO','HF PANCRED',180,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB TEPA ACREDIARIA','HF PANCRED',185,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ANTECIPAÇÃO','HF PANCRED',190,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIQ.BX R.I.','HF PANCRED',195,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('TRANSF AQUISICOES','HF PANCRED',199,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RECBTO VIA DOC/TED','HF PANCRED',200,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RECBTO VIA ESPECIE','HF PANCRED',201,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RECBTO DE SINISTRO','HF PANCRED',202,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RECBTO VIA CHEQUE','HF PANCRED',203,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RECBTO DESC EM FOLHA','HF PANCRED',204,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC 7 DIAS CEDIDAS','HF PANCRED',205,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('PAGTO VIA ASSESSORIA','HF PANCRED',206,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC MAIS 7 DIAS','HF PANCRED',207,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC LIBER ORDEM PGTO','HF PANCRED',208,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('PERDA OPERACIONAL','HF PANCRED',209,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIQ BX ANTEC MANUAL','HF PANCRED',210,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC LIB S/ FINANCEIRO','HF PANCRED',211,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC CONTR REFIN','HF PANCRED',212,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RETENÇÃO INADIMPLENCIA','HF PANCRED',213,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX PARC INADIMPLENCIA','HF PANCRED',214,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIQ BX ANTEC AUT','HF PANCRED',215,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DEP ID BRADESCO','HF PANCRED',216,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX DE CARTAO INSS','HF PANCRED',217,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX RECBTO POR OCT','HF PANCRED',218,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX REGULARIZ PAGT','HF PANCRED',219,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX PARC CRED CONSIG-GLOSA','HF PANCRED',220,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DEPOS IDENT - ITAU','HF PANCRED',221,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX CTR P/PENDENCIA FISICA','HF PANCRED',222,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BAIXA DESACORDO COMERCIAL','HF PANCRED',223,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX PRC CART PROP CES BRAD','HF PANCRED',224,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIQ CARTEIRA JUDCRED','HF PANCRED',225,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REAB PARC CESSAO BRADESC','HF PANCRED',226,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIQ CTRO- CESSAO BRADESCO','HF PANCRED',227,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX MIGRA CARTAO CONS','HF PANCRED',228,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC CTR-CONFISSAO DIVIDA','HF PANCRED',229,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('FRAUDE - PERDA DIRETA','HF PANCRED',230,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('PROC JUDICIAL - PERDA','HF PANCRED',231,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX P FRAUDE-CES BRADESCO','HF PANCRED',232,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX CTRO RECB CLI CES BRAD','HF PANCRED',233,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX CTT-FALTA DCTO FISICO','HF PANCRED',235,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX CTT-RECBTO CTA 5900052','HF PANCRED',236,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX CT-CTA590052-C DIVIDA','HF PANCRED',237,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC CTR-VLR REEMB CORBAN','HF PANCRED',238,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX CTT-RECBTO CTA 5900176','HF PANCRED',239,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REC A >LIQ P/OB-DEV GLOSA','HF PANCRED',240,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CR A DEV CTR AT-DEV GLOSA','HF PANCRED',241,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CNI CRED N IND-DEV GLOSA','HF PANCRED',242,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BAIXA FRAUDE OBITO','HF PANCRED',243,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX VIA REDIRECION-CONSIG','HF PANCRED',244,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CRED NAO IDENTIF','HF PANCRED',250,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CRED NAO IDENT INSS','HF PANCRED',251,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC ADTO RECOMPRA','HF PANCRED',253,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX REFINANCT INSS','HF PANCRED',254,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX CBR BRADESCO','HF PANCRED',255,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC LIBER TESOURARI','HF PANCRED',256,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX REC CETELEM','HF PANCRED',257,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX CP MONTE CRISTO','HF PANCRED',258,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX RECOMP CP ORG PUB','HF PANCRED',259,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('COR BX GOV RJ CARTAO','HF PANCRED',260,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX CDIV INSS','HF PANCRED',261,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BAIXA NAO ENTREGA ADF','HF PANCRED',262,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('OP BB','HF PANCRED',263,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX CTROS-PEND FISICO','HF PANCRED',264,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RECUPERACAO INADIMPLENCIA','HF PANCRED',265,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('AMORTIZACAO SALDO PORTAL','HF PANCRED',266,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX P/UTILIZ VL A REEM CLI','HF PANCRED',267,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX DEVOL.VALE POSTAL','HF PANCRED',268,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('PROCESSO JUDICIAL','HF PANCRED',270,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST LIQ CTR-CESSAO BRADES','HF PANCRED',271,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX PROC JUD BB 5664-2','HF PANCRED',272,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('VENCE TED','HF PANCRED',281,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('VENCE BOLETO','HF PANCRED',287,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BAIXA POR DESDOBRO','HF PANCRED',297,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO CHEQUE DEVOLVIDO','HF PANCRED',300,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO PARC ESPECIE','HF PANCRED',301,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO PRC P/ REEMB','HF PANCRED',302,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO DCC BANCOS','HF PANCRED',303,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO PARC-DESC PARCIAL','HF PANCRED',304,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO DE CTTS','HF PANCRED',305,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REABERTURA REFIN','HF PANCRED',306,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO BX PORTABILIDADE','HF PANCRED',307,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST PARCL-P/REEMB CORBAN','HF PANCRED',308,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO SUBSIDIOS DCOMB','HF PANCRED',309,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('TP BAIXA IOC','HF PANCRED',310,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO DCC CEF','HF PANCRED',311,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO DCC HSBC','HF PANCRED',312,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO DCC SANTANDER','HF PANCRED',313,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO DCC CASEBRAS','HF PANCRED',314,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO DCC ITAU','HF PANCRED',315,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST PARC BAIXADAS P/ADF','HF PANCRED',316,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST BX ASS N. PASCHOALOTT','HF PANCRED',317,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO BOLETO','HF PANCRED',320,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO ASSESSORIAS','HF PANCRED',321,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO EXTRATO','HF PANCRED',322,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO DEP. IDENTIFICADO','HF PANCRED',323,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO EQUATORIAL','HF PANCRED',324,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST- BX PARC CONSIG-GLOSA','HF PANCRED',325,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO CASEBRAS','HF PANCRED',326,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST BX PARC-REEMB FRAUDE','HF PANCRED',327,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO DCC PAULISTA','HF PANCRED',328,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO FRAUDE DETECTADA','HF PANCRED',330,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST PARCELA CONSIG - GRU','HF PANCRED',331,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST R >LIQ P/OB-DEV GLOS','HF PANCRED',340,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ET CR DEV CTR AT-DEV GLOS','HF PANCRED',341,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST CNI CR N IND-DEV GLOS','HF PANCRED',342,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST.BX CTROS-PEND.FISICO','HF PANCRED',343,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST.BAIXA FRAUDE OBITO','HF PANCRED',344,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST.BX CTR P/PEND.FISICA','HF PANCRED',345,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST BX CTT-RECB CT 590052','HF PANCRED',346,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST FRAUDE - PERDA DIRETA','HF PANCRED',347,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST PERDA PROC JUDICIAL','HF PANCRED',348,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB RECOMPRA','HF PANCRED',350,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC CP MONTE CRISTO','HF PANCRED',356,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC OPER CP ORG PUB','HF PANCRED',359,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST.BX.P/UTIL VL REEM CLI','HF PANCRED',367,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST. BX DEVOL.VALE POSTAL','HF PANCRED',368,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO PORTABILIDADE','HF PANCRED',370,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REJ A PROC - CONSIG','HF PANCRED',380,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DEV AUT P CLIENTES-CONSIG','HF PANCRED',390,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX PARC ANTECIPADA-CONSIG','HF PANCRED',400,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REIMPLANTE DE CTT','HF PANCRED',401,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ACERTO BOLETO','HF PANCRED',407,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ACERTO TED','HF PANCRED',411,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX LIQUIDA CTT','HF PANCRED',450,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ACERTO CORBAN','HF PANCRED',468,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RECBTO PORTABILIDADE','HF PANCRED',470,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ACERTO LIB TEPA ACREDIARI','HF PANCRED',485,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DCC BANCO HSBC','HF PANCRED',501,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DCC BANCO DO BRASIL','HF PANCRED',502,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DCC ABN AMRO REAL','HF PANCRED',503,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DCC BANCO BRADESCO','HF PANCRED',504,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DCC BANCO ITAU','HF PANCRED',505,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DCC MANAUSCREDITO','HF PANCRED',506,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DCC EQUATORIAL','HF PANCRED',507,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO EQUATORIAL','HF PANCRED',508,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DCC - CAIXA ECONOMICA','HF PANCRED',509,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DCC CASEBRAS','HF PANCRED',510,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DCC PAULISTA','HF PANCRED',511,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('OBITO - PANAMERICANA','HF PANCRED',550,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX REF RECBTO PAN SEGUROS','HF PANCRED',551,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('PAG HONOR ASSES COBR','HF PANCRED',552,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST PAG HONOR ASSES COBRA','HF PANCRED',553,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('PAGTO NOTIFIC COBRANCA','HF PANCRED',554,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST PG NOTIFIC COBRANCA','HF PANCRED',555,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('PG CUSTAS ASSES COBRANCA','HF PANCRED',556,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST PG CUSTAS ASSES COBRA','HF PANCRED',557,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ASSESSORIA FEMAK','HF PANCRED',601,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ASSESSORIA PERFIL','HF PANCRED',602,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ASSESSORIA NETWOK','HF PANCRED',603,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ASSESSORIA CRC','HF PANCRED',604,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ASSESSORIA MBM','HF PANCRED',605,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BOLETO AUTBANK IN28','HF PANCRED',606,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('OPERANDI','HF PANCRED',607,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ASSESSORIA JA REZEND','HF PANCRED',608,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ASSESSORIA WARM BRA','HF PANCRED',609,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RAFAEL PORDEUS CONS','HF PANCRED',610,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('JV AAC COB LTDA','HF PANCRED',611,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ASSESSORIA IZZI SOLUÇÕES','HF PANCRED',612,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('COBRANÇA PANAMERICANO','HF PANCRED',613,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ASSESSORIA ENTERCRED','HF PANCRED',614,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ASSESSORIA RBRASIL','HF PANCRED',615,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('RR SERVICOS','HF PANCRED',616,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX ASS NELSON PASCHOALOTT','HF PANCRED',617,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ASSESSORIA KITADO','HF PANCRED',618,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX VIA BOLETO-SMS','HF PANCRED',619,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO BOLETO','HF PANCRED',620,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO ASSESSORIAS','HF PANCRED',621,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO EXTRATO','HF PANCRED',622,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO DEP. IDENTIFICADO','HF PANCRED',623,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('INSS - PARC VIA BOLETO','HF PANCRED',650,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB.VALE POSTAL','HF PANCRED',666,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO LIB.VALE POSTAL','HF PANCRED',667,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIQ ANTECIP BOLETO','HF PANCRED',701,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BAIXA BOLETO','HF PANCRED',702,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BAIXA BOLETO COBRANCA','HF PANCRED',703,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST.BAIXA BOLETO COBRANCA','HF PANCRED',704,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANCEL LIB BOLETO','HF PANCRED',707,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANCEL LIB STR','HF PANCRED',711,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('PARC VIA BOLETO','HF PANCRED',750,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANCEL LIB TEP CORBAN','HF PANCRED',768,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANCEL LIB TEPA ACREDIARI','HF PANCRED',785,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BX DE ACORDO','HF PANCRED',800,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO DE ACORDO','HF PANCRED',801,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ESTORNO DE OPERAÇÃO','HF PANCRED',802,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BLOQUEIO-FINANC.REEMISSÃO','HF PANCRED',803,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('PAGTO RET PALIATIVO-VEIC','HF PANCRED',804,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EST-PAGTO RET PALIAT-VEIC','HF PANCRED',805,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANCEL ACERTO LIB BOLETO','HF PANCRED',807,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANCEL ACERTO LIB STR','HF PANCRED',811,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('EMP CONS-BX S/ FINANCEIRO','HF PANCRED',860,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('DESP SERV PROC DADOS-CONS','HF PANCRED',862,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC ACERT LIB TEP CORBAN','HF PANCRED',868,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CANC ACERT LIB TEPA ACRED','HF PANCRED',885,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('BOLETO COMPRA','HF PANCRED',900,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('TED COMPRA','HF PANCRED',901,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REEMBOLSO CORBAN COMPRA','HF PANCRED',902,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ACERTO COMPRA','HF PANCRED',903,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('ANTECIPAÇÃO COMPRA','HF PANCRED',904,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('PORTABILIDADE','HF PANCRED',955,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('CONSIG-REG CTROS FRAUDE','HF PANCRED',996,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('REG CTR DESDOBRO','HF PANCRED',997,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('GENÉRICO','HF PANCRED',998,GETDATE(),NULL,1)
INSERT INTO [gestao_reembolso].[HISTORICO_FINANCEIRO] VALUES('LIB ACERTO','HF PANCRED',999,GETDATE(),NULL,1)

GO

---------------------------------------------------------------------------------------------------------


-- SELECT * FROM [gestao_reembolso].[DEPARTAMENTO]
-- SELECT * FROM [gestao_reembolso].[SISTEMA]
-- SELECT * FROM [gestao_reembolso].[PRODUTO]
-- SELECT * FROM [gestao_reembolso].[CONTA]
-- SELECT * FROM [gestao_reembolso].[CONTA_RESERVA]
-- SELECT * FROM [gestao_reembolso].[COLIGADA]
-- SELECT * FROM [gestao_reembolso].[MENSAGEM_PADRAO]
-- SELECT * FROM [gestao_reembolso].[MENSAGEM_COMUNICACAO]
-- SELECT * FROM [gestao_reembolso].[HISTORICO_FINANCEIRO]

