USE [SSA]

GO

IF EXISTS(SELECT 1 FROM SYS.schemas WHERE NAME = 'gestao_reembolso')
BEGIN
	DROP SCHEMA [gestao_reembolso]
END

GO

CREATE SCHEMA [gestao_reembolso]

GO


-- ORDER DROP ------------------------------

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'REEMBOLSO_PAGAMENTO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[REEMBOLSO_PAGAMENTO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'REEMBOLSO_COMUNICACAO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[REEMBOLSO_COMUNICACAO]
END
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'COMUNICACAO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[COMUNICACAO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'MENSAGEM_COMUNICACAO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[MENSAGEM_COMUNICACAO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'REEMBOLSO_INTEGRACAO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[REEMBOLSO_INTEGRACAO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'CONTABIL_HISTORICO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[CONTABIL_HISTORICO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'HISTORICO_REEMBOLSO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[HISTORICO_REEMBOLSO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'EVENTO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[EVENTO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'REEMBOLSO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[REEMBOLSO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'PROCESSO_REGISTRO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[PROCESSO_REGISTRO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'SIGLA' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[SIGLA]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'DEPARTAMENTO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[DEPARTAMENTO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'ENDERECO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[ENDERECO] 
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'MENSAGEM_PAGAMENTO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[MENSAGEM_PAGAMENTO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'PAGAMENTO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[PAGAMENTO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'MENSAGEM' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[MENSAGEM]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'CONTA_RESERVA' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[CONTA_RESERVA] 
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'MENSAGEM_PADRAO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[MENSAGEM_PADRAO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'CONTRATO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[CONTRATO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'CONTABIL_PADRAO' AND TYPE = 'U')
BEGIN
	DROP TABLE gestao_reembolso.CONTABIL_PADRAO
END

GO 

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'PRODUTO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[PRODUTO]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'COLIGADA' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[COLIGADA]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'HISTORICO_FINANCEIRO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[HISTORICO_FINANCEIRO]
END

GO


IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'CLIENTE' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[CLIENTE]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'SISTEMA' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[SISTEMA]
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'CONTA_REJEICAO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[CONTA_REJEICAO] 
END

GO


IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'CONTA_CREDITO' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[CONTA_CREDITO] 
END

GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'CONTA' AND TYPE = 'U')
BEGIN
	DROP TABLE [gestao_reembolso].[CONTA] 
END

GO


---------------------------------------------------------
-- ORDER CREATE -----------------------------------------
CREATE TABLE [gestao_reembolso].[CLIENTE](
	ID_CLIENTE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NM_CLIENTE VARCHAR(200) NOT NULL,
	CD_TIPO_PESSOA CHAR(1) NOT NULL, 
	DS_REGISTRO_OBITO VARCHAR(30) NULL,	
	IC_OBITO CHAR(1) NULL DEFAULT '0',
	NO_CPF_CNPJ VARCHAR(15) NOT NULL,
	NO_DDD_CELULAR CHAR(3) NULL,
	NO_CELULAR VARCHAR(12) NULL,
	NO_DDD_FIXO CHAR(3) NULL,
	NO_FIXO VARCHAR(12) NULL,
)

GO

CREATE TABLE [gestao_reembolso].[CONTA](
	ID_CONTA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CD_TIPO_CONTA CHAR(2) NOT NULL, 
	NO_BANCO VARCHAR(5) NOT NULL, 
	NO_AGENCIA VARCHAR(10) NOT NULL,
	NO_DIGITO_AGENCIA CHAR(2) NULL, 
	NO_CONTA VARCHAR(15) NOT NULL, 
	NO_DIGITO_CONTA VARCHAR(2) NULL
)

GO

CREATE TABLE [gestao_reembolso].[SISTEMA](
	ID_SISTEMA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	DS_SISTEMA VARCHAR(50) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL DEFAULT GETDATE(),
	DT_ALTERACAO DATETIME NULL,
	IC_ATIVO CHAR(1) DEFAULT '1' 
)

GO

CREATE TABLE [gestao_reembolso].[COLIGADA](
	ID_COLIGADA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CD_COLIGADA VARCHAR(30) NOT NULL, 
	NM_COLIGADA VARCHAR(100) NOT NULL,
	CNPJ_COLIGADA VARCHAR(15) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL DEFAULT GETDATE(),
	DT_ALTERACAO DATETIME NULL,
	IC_ATIVO CHAR(1) DEFAULT '1'
)

GO
CREATE TABLE [gestao_reembolso].[HISTORICO_FINANCEIRO](
	ID_HISTORICO_FINANCEIRO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	DS_MOTIVO VARCHAR(50) NOT NULL,
	DS_ORIGEM_INFORMACAO VARCHAR(30) NOT NULL,
	CD_HISTORICO_FINANCEIRO INT NOT NULL ,
	DT_INCLUSAO DATETIME NOT NULL DEFAULT GETDATE(),
	DT_ALTERACAO DATETIME NULL,
	IC_ATIVO CHAR(1) DEFAULT '1'
)
GO

CREATE TABLE [gestao_reembolso].[DEPARTAMENTO](
	ID_DEPARTAMENTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CD_DEPARTAMENTO VARCHAR(15) NOT NULL, 
	DS_DEPARTAMENTO VARCHAR(50) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL DEFAULT GETDATE(),
	DT_ALTERACAO DATETIME NULL,
	IC_ATIVO CHAR(1) DEFAULT '1' 
)

GO

CREATE TABLE [gestao_reembolso].[SIGLA](
	ID_SIGLA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CD_SIGLA VARCHAR(20) NOT NULL, 
	DS_SIGLA VARCHAR(50) NOT NULL, 
	DT_INCLUSAO DATETIME NOT NULL DEFAULT GETDATE(),
	DT_ALTERACAO DATETIME NULL,
	IC_ATIVO CHAR(1) DEFAULT '1'
)

GO
CREATE TABLE [gestao_reembolso].[EVENTO](
	ID_EVENTO [INT] IDENTITY (1,1) NOT NULL PRIMARY KEY,
	CD_EVENTO [VARCHAR](70) NOT NULL ,
	IC_CONTABIL [CHAR] NOT NULL ,
	CD_FLUXO [VARCHAR](45) NOT NULL 
)
CREATE TABLE [gestao_reembolso].[REEMBOLSO_INTEGRACAO](
	ID_INTEGRACAO 			INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_REEMBOLSO  			BIGINT NULL,
	ID_LOTE					VARCHAR(50) NULL,
	CD_LOTE_INTEGRACAO		VARCHAR(50) NULL,
	CD_STATUS_INTEGRACAO  	VARCHAR(50) NULL,
	DS_MENSAGEM_ERRO  		VARCHAR(100) NULL,
	DT_INTEGRACAO  			DATETIME NULL,
	NM_CLIENTE  			VARCHAR(50) NULL, 
	NO_CONTRATO 			VARCHAR(50) NULL,
	VL_REEMBOLSO  			DECIMAL(9,2) NULL,
	NM_CONVENIO 			VARCHAR(50) NULL,
	CD_MATRICULA  			VARCHAR(50) NULL,
	NO_CPF_CNPJ  			VARCHAR(50) NULL,
	NO_MES_COMPETENCIA 		INT NULL,	
	NO_ANO_COMPETENCIA 		INT NULL,	
	CD_SIGLA 				VARCHAR(50) NULL,
	CD_PROCESSO_ENTRADA 	VARCHAR(50) NULL,
	CD_PRODUTO 				VARCHAR(50) NULL,
	CD_USUARIO_INCLUSAO  	VARCHAR(50) NULL,
	DT_INCLUSAO  			DATETIME NOT NULL DEFAULT GETDATE()
)

GO

CREATE TABLE [gestao_reembolso].[MENSAGEM_COMUNICACAO](
	ID_MENSAGEM_COMUNICACAO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	DS_MENSAGEM_COMUNICACAO VARCHAR(MAX) NOT NULL,
	CD_TIPO_COMUNICACAO VARCHAR(15) NOT NULL, 
	DT_INCLUSAO DATETIME NOT NULL DEFAULT GETDATE()
)

GO
--//--
CREATE TABLE [gestao_reembolso].[ENDERECO](
	ID_ENDERECO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_CLIENTE INT NOT NULL REFERENCES [gestao_reembolso].[CLIENTE](ID_CLIENTE),
	NM_LOGRADOURO VARCHAR(150) NULL,
	NO_ENDERECO VARCHAR(10) NULL, 
	DS_COMPLEMENTO VARCHAR(30) NULL,
	NO_CEP VARCHAR(8) NULL,
	NM_BAIRRO VARCHAR(80) NULL,
	NM_CIDADE VARCHAR(80) NULL,
	CD_UF CHAR(2) NULL, 
	DT_ATUALIZACAO DATETIME NOT NULL DEFAULT GETDATE()
)

GO

CREATE TABLE [gestao_reembolso].[CONTA_CREDITO](
	ID_CONTA INT NOT NULL REFERENCES [gestao_reembolso].[CONTA](ID_CONTA) PRIMARY KEY,
	ID_CLIENTE INT NOT NULL REFERENCES [gestao_reembolso].[CLIENTE](ID_CLIENTE), 
	DT_ATUALIZACAO DATETIME NOT NULL DEFAULT GETDATE()
)

GO

CREATE TABLE [gestao_reembolso].[PRODUTO](
	ID_PRODUTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CD_PRODUTO VARCHAR(20) NOT NULL,
	NM_PRODUTO VARCHAR(25) NOT NULL,
	CD_CARTEIRA VARCHAR(10) NOT NULL,
	ID_SISTEMA INT NOT NULL REFERENCES [gestao_reembolso].[SISTEMA](ID_SISTEMA), 
	DT_INCLUSAO DATETIME NOT NULL DEFAULT GETDATE(),
	DT_ALTERACAO DATETIME NULL,
	IC_ATIVO CHAR(1) DEFAULT '1' 
)

GO

CREATE TABLE [gestao_reembolso].[CONTRATO](
	ID_CONTRATO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CD_CONTRATO VARCHAR(40) NOT NULL,
	CD_STATUS_CONTRATO [varchar](20) NULL,
	NM_CONVENIO [varchar](50) NULL,
	DT_STATUS DATETIME NULL,
	ID_PRODUTO INT NOT NULL REFERENCES [gestao_reembolso].[PRODUTO](ID_PRODUTO),
	ID_CLIENTE INT NOT NULL REFERENCES [gestao_reembolso].[CLIENTE](ID_CLIENTE),
	ID_COLIGADA INT NOT NULL REFERENCES [gestao_reembolso].[COLIGADA](ID_COLIGADA),
	ID_HISTORICO_FINANCEIRO INT NOT NULL REFERENCES [gestao_reembolso].[HISTORICO_FINANCEIRO](ID_HISTORICO_FINANCEIRO)
)

GO

CREATE TABLE gestao_reembolso.CONTABIL_PADRAO(
	ID_CONTABIL_PADRAO INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	ID_PRODUTO INT NOT NULL FOREIGN KEY REFERENCES gestao_reembolso.PRODUTO(ID_PRODUTO), 
	CD_PROCESSO VARCHAR(50) NULL,
	CD_LAYOUT VARCHAR(30) NULL,	
	CD_COLIGADA	VARCHAR(3) NULL,	
	CD_SISTEMA VARCHAR(8) NULL,	
	NO_SEQUENCIA_ORIGEM VARCHAR(2) NULL,
	CD_EMPRESA_ORIGEM VARCHAR(3) NULL,	
	CD_AGENCIA VARCHAR(5) NULL,	
	CD_UNIDADE VARCHAR(5) NULL,	
	CD_NIVEL1 VARCHAR(5) NULL,	
	CD_NIVEL2 VARCHAR(5) NULL,	
	CD_NIVEL3 VARCHAR(5) NULL,	
	CD_NIVEL4 VARCHAR(5) NULL,	
	CD_DEBITA_CREDITA VARCHAR(1) NULL,	
	CD_AGENCIA_DESTINO VARCHAR(5) NULL,	
	CD_NIVEL1_DESTINO VARCHAR(5) NULL,	
	CD_NIVEL2_DESTINO VARCHAR(5) NULL,	
	CD_NIVEL3_DESTINO VARCHAR(5) NULL,	
	CD_NIVEL4_DESTINO VARCHAR(5) NULL,	
	CD_UNIDADE_DESTINO VARCHAR(5) NULL,	
	DS_COMPLEMENTO2 VARCHAR(30) NULL,	
	DS_COMPLEMENTO3 VARCHAR(30) NULL,	
	DS_COMPLEMENTO4 VARCHAR(30) NULL,	
	DS_COMPLEMENTO5 VARCHAR(30) NULL,	
	CD_FORMA_LANCAMENTO	VARCHAR(2) NULL,	
	CD_TIPO_LANCAMENTO VARCHAR(1) NULL,	
	CD_EVENTO VARCHAR(5) NULL,	
	NO_SEQUENCIA_ITEM VARCHAR(2) NULL,	
	NM_TABELA_DEBITO VARCHAR(6) NULL,	
	CD_PRODUTO_DEBITO VARCHAR(10) NULL,	
	CD_TIPO_CREDITO_DEBITO VARCHAR(2) NULL,	
	CD_ATIVIDADE_DEBITO	VARCHAR(5) NULL,	
	CD_TIPO_CONTA_DEBITO VARCHAR(10) NULL,	
	NO_CONTA_DEBITO VARCHAR(15) NULL,	
	CD_REDUZIDO_DEBITO	VARCHAR(8) NULL,	
	NO_CONTA_AUXILIAR_DEBITO VARCHAR(10) NULL,	
	NO_CONTA_CORRENTE_DEBITO VARCHAR(10) NULL,	
	NM_TABELA_CREDITO VARCHAR(6) NULL,	
	CD_PRODUTO_CREDITO VARCHAR(10) NULL,	
	CD_TIPO_CREDITO_CREDITO VARCHAR(2) NULL,	
	CD_ATIVIDADE_CREDITO VARCHAR(5) NULL,	
	CD_TIPO_CONTA_CREDITO VARCHAR(10) NULL,	
	NO_CONTA_CREDITO VARCHAR(15) NULL,	
	CD_REDUZIDO_CREDITO VARCHAR(8) NULL,	
	NO_CONTA_AUXILIAR_CREDITO VARCHAR(10) NULL,	
	NO_CONTA_CORRENTE_CREDITO VARCHAR(10) NULL,	
	CD_TIPO_MOEDA VARCHAR(10) NULL,	
	QT_MOEDA VARCHAR(20) NULL,	
	VL_MOEDA VARCHAR(20) NULL,	
	IC_REPROCESSAMENTO VARCHAR(1) NULL,	
	CD_GERENTE VARCHAR(7) NULL,	
	NO_DOCUMENTO VARCHAR(10) NULL,	
	IC_ATUALIZADO VARCHAR(1) NULL,	
	IC_CANCELADO VARCHAR(1) NULL,	
	IC_ESTORNADO VARCHAR(1) NULL,	
	DT_INCLUSAO DATETIME NOT NULL DEFAULT GETDATE() 
)

GO

CREATE TABLE [gestao_reembolso].[CONTA_REJEICAO](
	ID_CONTA INT NOT NULL REFERENCES [gestao_reembolso].[CONTA](ID_CONTA) PRIMARY KEY,
	ID_CLIENTE INT NOT NULL REFERENCES [gestao_reembolso].[CLIENTE](ID_CLIENTE), 
	DS_ERRO VARCHAR(50) NULL,
	DT_ATUALIZACAO DATETIME NOT NULL DEFAULT GETDATE()
)

GO

CREATE TABLE [gestao_reembolso].[MENSAGEM_PADRAO](
	ID_MENSAGEM_PADRAO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_PRODUTO INT NOT NULL REFERENCES  [gestao_reembolso].[PRODUTO](ID_PRODUTO),
	CD_FINALIDADE_SPB VARCHAR(20) NOT NULL,
	IC_CREDITA_CONTA_CORRENTE CHAR(1) NOT NULL,
	IC_DEBITA_CONTA_CORRENTE CHAR(1) NOT NULL,
	IC_EMITE_RECEBE CHAR(1) NOT NULL,
	IC_MESMA_TITULARIDADE CHAR(1) NOT NULL, 
	IC_PREVISAO CHAR(1) NOT NULL,
	IC_TRANSITA_CONTA_CORRENTE CHAR(1) NOT NULL,
	NO_BORDERO VARCHAR(30) NOT NULL, 
	CD_TIPO_LIQUIDACAO VARCHAR(15) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL DEFAULT GETDATE()
)

GO

CREATE TABLE [gestao_reembolso].[CONTA_RESERVA](
	ID_CONTA INT NOT NULL REFERENCES [gestao_reembolso].[CONTA](ID_CONTA) PRIMARY KEY,
	NO_CNPJ_SACADO VARCHAR(15) NOT NULL,
	NO_SEQUENCIA_SACADO CHAR(1) NOT NULL, 
	NM_SACADO VARCHAR(150) NOT NULL, 
	CD_TIPO_PESSOA_SACADO CHAR(1) NOT NULL 
)

GO

CREATE TABLE [gestao_reembolso].[MENSAGEM](
	ID_MENSAGEM INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_MENSAGEM_PADRAO INT NOT NULL REFERENCES [gestao_reembolso].[MENSAGEM_PADRAO](ID_MENSAGEM_PADRAO),
	NO_REQUISICAO VARCHAR(30) NULL, 
	DT_REGISTRO DATETIME NOT NULL DEFAULT GETDATE(),
	DT_LIQUIDACAO DATETIME NULL, 
	CD_STATUS_MENSAGEM VARCHAR(20),
	ID_CONTA_RESERVA INT NOT NULL REFERENCES [gestao_reembolso].[CONTA_RESERVA](ID_CONTA),
	ID_CONTA_CREDITO INT NOT NULL REFERENCES [gestao_reembolso].[CONTA_CREDITO](ID_CONTA)
)
GO

CREATE TABLE [gestao_reembolso].[PAGAMENTO](
	ID_PAGAMENTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_COLIGADA INT NOT NULL REFERENCES [gestao_reembolso].[COLIGADA](ID_COLIGADA), 
	DT_REGISTRO_PAGAMENTO DATETIME NOT NULL DEFAULT GETDATE(),
	DT_PAGAMENTO DATETIME NULL,
	CD_TIPO_PAGAMENTO VARCHAR(15), 
	VL_PAGAMENTO DECIMAL(9,2) NOT NULL
)

GO

CREATE TABLE [gestao_reembolso].[MENSAGEM_PAGAMENTO](
	ID_MENSAGEM INT NOT NULL REFERENCES [gestao_reembolso].[MENSAGEM](ID_MENSAGEM),
	ID_PAGAMENTO INT NOT NULL REFERENCES [gestao_reembolso].[PAGAMENTO](ID_PAGAMENTO),
	CONSTRAINT PK_ID_MENSAGEM_ID_PAGAMENTO PRIMARY KEY CLUSTERED (ID_PAGAMENTO,ID_MENSAGEM) 
)

GO


CREATE TABLE [gestao_reembolso].[PROCESSO_REGISTRO](
	ID_PROCESSO_REGISTRO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CD_PROCESSO_REGISTRO INT NOT NULL,
	DS_PROCESSO_REGISTRO VARCHAR(30) NOT NULL, 
	CD_CENTRO_CUSTO VARCHAR(10) NULL,
	CD_MODELO_CONTABIL VARCHAR(10) NULL,
	CD_FLUXO VARCHAR(10) NULL,
	CD_CONTA_DEBITO VARCHAR(20) NULL,
	CD_CONTA_CREDITO VARCHAR(20) NULL,
	CD_MODELO_CONTABIL_REVERSAO VARCHAR(10) NULL,	
	CD_CONTA_DEBITO_REVERSAO VARCHAR(20) NULL,
	CD_CONTA_CREDITO_REVERSAO VARCHAR(20) NULL,
	ID_EVENTO int NULL REFERENCES [gestao_reembolso].[EVENTO](ID_EVENTO), 
	ID_EVENTO_ESTORNO int NULL REFERENCES [gestao_reembolso].[EVENTO](ID_EVENTO),
	DT_INCLUSAO DATETIME NOT NULL DEFAULT GETDATE(),
	DT_ALTERACAO DATETIME NULL,
	IC_ATIVO CHAR(1) DEFAULT '1'
)

GO


CREATE TABLE [gestao_reembolso].[REEMBOLSO](
	ID_REEMBOLSO BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_LOTE_REEMBOLSO INT NOT NULL,
	CD_USUARIO_INCLUSAO VARCHAR(50) NOT NULL, 
	CD_USUARIO_ALTERACAO VARCHAR(50) NULL, 
	CD_USUARIO_APROVACAO VARCHAR(50) NULL, 
	ID_DEPARTAMENTO INT NOT NULL REFERENCES [gestao_reembolso].[DEPARTAMENTO](ID_DEPARTAMENTO),
	ID_CONTRATO INT NOT NULL REFERENCES [gestao_reembolso].[CONTRATO](ID_CONTRATO),
	ID_SIGLA INT NULL REFERENCES [gestao_reembolso].[SIGLA](ID_SIGLA),
	ID_PROCESSO_REGISTRO INT NULL REFERENCES [gestao_reembolso].[PROCESSO_REGISTRO](ID_PROCESSO_REGISTRO),
	DT_SOLICITACAO DATETIME NOT NULL,
	CD_STATUS_REEMBOLSO VARCHAR(20) NOT NULL, 
	VL_REEMBOLSO DECIMAL(9,2) NOT NULL,
	NO_MES_COMPETENCIA INT NULL,	
	NO_ANO_COMPETENCIA INT NULL,
	DS_ERRO VARCHAR(250) NULL,
	DT_INCLUSAO DATETIME NOT NULL DEFAULT GETDATE()
)

GO

CREATE TABLE [gestao_reembolso].[HISTORICO_REEMBOLSO](
	[ID_HISTORICO_REEMBOLSO] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[ID_REEMBOLSO] [bigint] NOT NULL REFERENCES [gestao_reembolso].REEMBOLSO(ID_REEMBOLSO),
	[ID_EVENTO] [int] NOT NULL REFERENCES [gestao_reembolso].[EVENTO](ID_EVENTO),
	[DT_EVENTO] [datetime] NOT NULL DEFAULT GETDATE(),
	[CD_STATUS_INICIO] [varchar](20) NOT NULL,
	[CD_STATUS_FIM] [varchar](20) NOT NULL,
	[CD_USUARIO_INCLUSAO] [varchar](50) NULL,
	[CD_STASTUS_CONTABIL] [varchar](20) NULL,
	DS_ERRO VARCHAR(250) NULL
)
GO

CREATE TABLE [gestao_reembolso].[CONTABIL_HISTORICO](
	[ID_CONTABIL_HISTORICO] [int] IDENTITY(1,1) NOT NULL,
	[ID_CONTABIL_PADRAO] [int] NOT NULL,
	[NO_REGISTRO] [varchar](20) NULL,
	[DT_SISTEMA] [varchar](10) NULL,
	[NO_REMESSA] [varchar](6) NULL,
	[NO_ORIGEM] [varchar](10) NULL,
	[NO_SEQUENCIA_ORIGEM] [varchar](2) NULL,
	[DT_LANCAMENTO] [varchar](10) NULL,
	[VL_ENTRADA] [numeric](17, 2) NULL,
	[DS_HISTORICO] [varchar](4) NULL,
	[DS_COMPLEMENTO1] [varchar](30) NULL,
	[NO_MODELO] [varchar](5) NULL,
	[NO_CENTRO_CUSTO_DEBITO] [varchar](7) NULL,
	[NO_CENTRO_CUSTO_CREDITO] [varchar](7) NULL,
	[DT_DOCUMENTO] [varchar](10) NULL,
	[DT_ULTIMA_ATUALIZACAO] [varchar](30) NULL,
	[CD_USUARIO] [varchar](50) NULL,
	[NM_ARQUIVO_INTEGRADO] [varchar](50) NULL,
	[DT_INTEGRACAO] [datetime] NOT NULL,
	[ID_HISTORICO_REEMBOLSO] [int] NULL,
	[CD_STATUS_CONTABILIDADE] [varchar](20) NULL,
	[DS_MENSAGEM_CONTABILIDADE] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CONTABIL_HISTORICO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [gestao_reembolso].[CONTABIL_HISTORICO] ADD  DEFAULT (getdate()) FOR [DT_INTEGRACAO]
GO

ALTER TABLE [gestao_reembolso].[CONTABIL_HISTORICO]  WITH CHECK ADD FOREIGN KEY([ID_CONTABIL_PADRAO])
REFERENCES [gestao_reembolso].[CONTABIL_PADRAO] ([ID_CONTABIL_PADRAO])
GO

ALTER TABLE [gestao_reembolso].[CONTABIL_HISTORICO]  WITH CHECK ADD FOREIGN KEY([ID_HISTORICO_REEMBOLSO])
REFERENCES [gestao_reembolso].[HISTORICO_REEMBOLSO] ([ID_HISTORICO_REEMBOLSO])
GO



CREATE TABLE [gestao_reembolso].[COMUNICACAO](
	ID_COMUNICACAO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_MENSAGEM_COMUNICACAO INT NOT NULL REFERENCES [gestao_reembolso].[MENSAGEM_COMUNICACAO](ID_MENSAGEM_COMUNICACAO),
	DT_ENVIO DATETIME NOT NULL 
) 
GO

CREATE TABLE [gestao_reembolso].[REEMBOLSO_COMUNICACAO](
	ID_REEMBOLSO BIGINT NOT NULL REFERENCES [gestao_reembolso].[REEMBOLSO](ID_REEMBOLSO),
	ID_COMUNICACAO INT NOT NULL REFERENCES [gestao_reembolso].[COMUNICACAO](ID_COMUNICACAO),
	CONSTRAINT PK_ID_REEMBOLSO_ID_COMUNICACAO PRIMARY KEY CLUSTERED (ID_REEMBOLSO,ID_COMUNICACAO) 
)
 
GO

CREATE TABLE [gestao_reembolso].[REEMBOLSO_PAGAMENTO](
	ID_PAGAMENTO INT NOT NULL REFERENCES [gestao_reembolso].[PAGAMENTO](ID_PAGAMENTO),
	ID_REEMBOLSO BIGINT NOT NULL REFERENCES [gestao_reembolso].[REEMBOLSO](ID_REEMBOLSO),
	CONSTRAINT PK_ID_REEMBOLSO_ID_PAGAMENTO PRIMARY KEY CLUSTERED (ID_PAGAMENTO,ID_REEMBOLSO) 
)

GO

---------------------------------------------------------
--IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'PROCESSO_JUDICIAL' AND TYPE = 'U')
--BEGIN
--	DROP TABLE [gestao_reembolso].[PROCESSO_JUDICIAL]
--END

--GO

--CREATE TABLE [gestao_reembolso].[PROCESSO_JUDICIAL](
--	ID_PROCESSO INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
--	ID_CONTRATO INT NOT NULL REFERENCES [gestao_reembolso].[CONTRATO](ID_CONTRATO), 
--	ID_PROCESSO_SISTEMA_ORIGEM INT NOT NULL, 
--	DS_TITULO_PROCESSO VARCHAR(500) NULL 
--)
--GO
