
USE [SSA]
GO

/****** Object:  Table [gestao_reembolso].[LOTE_REEMBOLSO]    Script Date: 29/08/2018 16:16:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [gestao_reembolso].[LOTE_REEMBOLSO](
	[ID_LOTE] [int] IDENTITY(1,1) NOT NULL,
	[DS_LOTE] [varchar](50) NOT NULL,
	[DT_INCLUSAO] [datetime] NOT NULL,
	[DT_ALTERACAO] [datetime] NULL,
	[IC_ATIVO] [char](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_LOTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [gestao_reembolso].[LOTE_REEMBOLSO] ADD  DEFAULT (getdate()) FOR [DT_INCLUSAO]
GO

ALTER TABLE [gestao_reembolso].[LOTE_REEMBOLSO] ADD  DEFAULT ('1') FOR [IC_ATIVO]
GO

