use CDCPAN


SELECT 
	EFNROPER, 
	HFDESCR 
FROM 
	CDCPAN.SYSFUNC.EFINA -- historico financeiro do contrato
	INNER JOIN CDCPAN.SYSFUNC.THFIN -- dominio historico financeiro 
		ON EFCODMOV = HFCODMOV 
WHERE 
	EFNROPER = '720434576-8' 
 

 -- qry poara utilizar no sistema 

 SELECT OPNROPER, OPDTLIQ, CASE WHEN ISNULL(OPESTORNO,'N')='S' THEN 'SIM' ELSE 'NÃO' END ESTONADA,
(SELECT TOP 1 CONVERT(VARCHAR,HFCODMOV)+' - '+ HFDESCR 
				FROM CDCPAN.SYSFUNC.EFINA (NOLOCK)
				INNER JOIN CDCPAN.SYSFUNC.THFIN (NOLOCK) ON HFCODMOV=EFCODMOV
				WHERE EFNROPER=OPNROPER AND EFDTMOV=OPDTLIQ ORDER BY EFNRPARC DESC)
HIST_LIQ
FROM CDCPAN.SYSFUNC.COPER (NOLOCK)
WHERE 
--OPDTLIQ='2018-08-10'
OPNROPER = '321140824-4' 